[workspace]
members = ["projects/*"]
default-members = [
    "projects/jupyter",
    "projects/jupyter-calculator",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
