[package]
name = "evcxr_jupyter"
version = "0.14.2"
license = "MIT OR Apache-2.0"
description = "A Jupyter Kernel for Rust"
repository = "https://github.com/evcxr/evcxr"
readme = "README.md"
authors = ["The Evcxr Authors"]
edition = "2021"
rust-version = "1.57"

[dependencies]
clap = "4.2.7"
clap_derive = "4.2.0"
#evcxr = { version = "=0.14.2", path = "../evcxr" }
serde = "1.0.163"
serde_json = "1.0.96"
serde_derive = "1.0.163"
bytes = "1.2.1"
tokio = "1.24.2"
uuid = { version = "1.1.2", features = ["v4"] }
hmac = "0.12.0"
sha2 = "0.10.0"
hex = "0.4.2"
colored = "2.0.0"
dirs = "5.0.1"
chrono = "0.4.19"
unicode-segmentation = "1.7.1"
generic-array = "0.14.4"
crossbeam-channel = "0.5.5"
ariadne = "0.2.0"
zeromq = { version = "0.3.3", default_features = false, features = ["tokio-runtime", "tcp-transport"] }

[features]
default = []
