[package]
name = "jupyter"
version = "0.0.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
description = "Jupyter client written in Rust"
homepage = "https://github.com/oovm/jupyter-protocol"
repository = "https://github.com/oovm/jupyter-protocol"
documentation = "https://docs.rs/jupyter"
readme = "README.md"
license = "Apache-2.0"
edition = "2018"

[dependencies]
zmq = "0.10.0"
serde = "1.0.163"
serde_json = "1.0.96"
serde_derive = "1.0.163"
uuid = { version = "1.3.3", features = ["v4"] }
hmac = "0.12.1"
sha2 = "0.10.6"
hex = "0.4.3"
log = "0.4.17"
failure = "0.1.8"
digest = "0.10.6"
chrono = "0.4.24"
dirs = "5.0.1"
glob = "0.3.1"

[dev-dependencies]
structopt = "0.3.26"
env_logger = "0.10.0"
crypto-mac = "0.11.1"
generic-array = "0.14.7"
