[package]
name = "jupyter"
version = "0.1.2"
license = "MIT OR Apache-2.0"
description = "Jupyter Kernel Protocol in Rust"
homepage = "https://github.com/oovm/jupyter-protocol/tree/dev/projects/jupyter-calculator"
repository = "https://github.com/oovm/jupyter-protocol"
documentation = "https://docs.rs/jupyter"
keywords = ["jupyter", "kernel", "protocol"]
categories = ["science"]
readme = "readme.md"
authors = ["The Evcxr Authors"]
edition = "2021"
exclude = ["third_party/.ipynb_checkpoints/"]

[dependencies]
clap = "4.2.7"
clap_derive = "4.2.0"
serde = "1.0.163"
serde_json = "1.0.96"
serde_derive = "1.0.163"
url = "2.3.1"
bytes = "1.2.1"
tokio = "1.24.2"
uuid = { version = "1.1.2", features = ["v4", "serde"] }
hmac = "0.12.0"
sha2 = "0.10.0"
hex = "0.4.2"
colored = "2.0.0"
dirs = "5.0.1"
chrono = { version = "0.4.19", features = ["serde"] }
unicode-segmentation = "1.7.1"
generic-array = "0.14.4"
crossbeam-channel = "0.5.5"
syntax-error = "0.0.1"
async-trait = "0.1.68"
zeromq = { version = "0.3.3", default_features = false, features = ["tokio-runtime", "tcp-transport"] }

[features]
default = []
