[package]
name = "calculator"
publish = false
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "Jupyter Kernel Protocol in Rust"
repository = "https://github.com/oovm/jupyter-protocol"
readme = "README.md"
authors = ["The Evcxr Authors"]
edition = "2021"
exclude = []

[dependencies]
num = "0.4.0"
toml = "0.7.3"
clap = "4.2.7"
clap_derive = "4.2.0"
mathml-core = "0.1.5"
mathml-latex = "0.0.3"
svg = "0.13.1"
tracing-subscriber = "0.3.17"
image = "0.24.6"
base64 = "0.21.0"

[dependencies.jupyter]
version = "*"
path = "../jupyter"
features = ["url", "image", "mathml-core", "svg"]

[dependencies.jupyter-derive]
version = "*"
path = "../jupyter-derive"
